language: minimal

branches:
  except:
  - /^blackfire-.*$/
  - prepare-release

notifications:
  email:
    on_success: never

services:
  - docker

env:
  # Some super slow extension first
  - LAYER=imagick PHP="73 74"
  - LAYER=memcached PHP="73 74"
  - LAYER=grpc PHP="73 74"
  # All layers in alphabetical order
  - LAYER=amqp PHP="73 74"
  - LAYER=blackfire PHP="73 74"
  - LAYER=cassandra PHP="73 74"
  - LAYER=ds PHP="73 74 80"
  - LAYER=gd PHP="73 74 80"
  - LAYER=gmp PHP="73 74 80"
  - LAYER=igbinary PHP="73 74 80"
  - LAYER=ldap PHP="73 74 80"
  - LAYER=mailparse PHP="73 74 80"
  - LAYER=mongodb PHP="73 74"
  - LAYER=msgpack PHP="73 74"
  - LAYER=odbc-snowflake PHP="73 74 80"
  - LAYER=pcov PHP="73 74 80"
  - LAYER=pgsql PHP="73 74 80"
  - LAYER=redis PHP="73 74 80"
  - LAYER=scrypt PHP="73 74"
  - LAYER=sqlsrv PHP="73 74"
  - LAYER=uuid PHP="73 74 80"
  - LAYER=xdebug PHP="73 74 80"
  - LAYER=yaml PHP="73 74 80"

before_install:
  - |
    # tfold is a helper to create folded reports (From Symfony)
    tfold () {
        local title="$1"
        local fold=$(echo $title | sed -r 's/[^-_A-Za-z0-9]+/./g')
        shift
        echo -e "travis_fold:start:$fold"
        echo -e "\\e[1;34m$title\\e[0m"
        bash -xc "$*" 2>&1
        local ok=$?
        (exit $ok) &&
            echo -e "\\e[32mOK\\e[0m $title\\n\\ntravis_fold:end:$fold" ||
            echo -e "\\e[41mKO\\e[0m $title\\n"
        (exit $ok)
    }
    export -f tfold

script:
  - cd layers/$LAYER
  - |
    for php_version in $PHP; do
      tfold "Build $php_version" docker build --build-arg PHP_VERSION=${php_version} .
    done
