language: php

notifications:
  email:
    on_success: never

services:
  - docker

env:
  - LAYER=amqp PHP="72 73 74"
  - LAYER=blackfire PHP="72 73 74"
  - LAYER=xdebug PHP="72 73 74"

script:
  - cd layers/$LAYER
  - set -e ;
    for php_version in $PHP; do ;
    echo "##\n#\n#\n PHP Version ${php_version}\n\n";
    docker build --build-arg PHP_VERSION=${php_version} . ;
    done
